name: new-tag

on:
  issues:
    types: [opened, edited]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create md file
        uses: actions/github-script@v4
        with:
          script: |
            const title = ${{ github.event.issue.title }}
            const body = ${{ github.event.issue.body }}
            printf body > ${{ github.event.issue.title }}.md