name: new-tag

on:
  issues:
    types: [opened, edited]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        echo First        > other.txt
        echo Second Line >> other.txt
        echo Third       >> other.txt