name: new-tag

on:
  issues:
    types: [opened, edited]
	

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create md file
        uses: actions/github-script@v4
        with:
          script: |
            const title = ${{ github.event.issue.title }}
            const body = ${{ github.event.issue.body }}
            const text = "## " + ${{ github.event.issue.title }} + "\n\n" + body.substring(body.indexOf("name") - 1, body.indexOf("### Example")-1)
            printf text > current-tags/${{ github.event.issue.title }}.md