name: new-tag

on:
  issues:
    types: [opened, edited]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create file
      run: |
        ls -la ~/
        mkdir ~/.zorg
        echo First        > ~/.zorg/home.txt
        echo Second Line >> ~/.zorg/home.txt
        echo Third       >> ~/.zorg/home.txt
        ls -la ~/.zorg/