name: new-tag

on:
  issues:
    types: [opened, edited]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create md file
        uses: "finnp/create-file-action@master"
          env:
            FILE_NAME: "fileName.txt"
            FILE_DATA: ${{ github.event.issue.body }}